version: '3.9'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: monitor_portal_db
      MYSQL_USER: monitor_user
      MYSQL_PASSWORD: monitor_password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - monitor_network

  backend:
    build: ./backend
    restart: always
    command: /app/entrypoint.sh
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    environment:
      DB_ENGINE: django.db.backends.mysql
      DB_NAME: monitor_portal_db
      DB_USER: monitor_user
      DB_PASSWORD: monitor_password
      DB_HOST: db
      DB_PORT: 3306
      DEBUG: 'False'
      ALLOWED_HOSTS: 'backendmbinfrawatch.marketbytes.in'
      SECRET_KEY: 'CHANGE_THIS_NOW'
    depends_on:
      - db
    networks:
      - monitor_network

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: https://backendmbinfrawatch.marketbytes.in
    restart: always
    networks:
      - monitor_network

networks:
  monitor_network:

volumes:
  db_data:
  static_volume:
  media_volume:
